spring:
  config:
    import: optional:.env[.properties]

  datasource:
    url: ${AWS_DB_ENDPOINT}
    username: ${AWS_DB_ID}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH2_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH2_CLIENT_SECRET}
            scope:
              - account_email
              - name
              - phone_number
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post

          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_PASSWORD}
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
